# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kemitix Code
email: pcampbell@kemitix.net
url: "https://kemitix.github.io"
github_username: kemitix

permalink: /:year/:month/:day/:title/
markdown: kramdown
#sass:
#  sass-dir: _sass
#  style: compressed
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_codary: false
exclude: ["Gemfile", "Gemfile.lock", ".idea"]
comments: true

# Build settings
theme: minima
remote_theme: mmistakes/so-simple-theme
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist

author:
  name: Paul Campbell
  picture: images/paul-campbell.jpg
  email: pcampbell@kemitix.net
  twitter:
  facebook:
  github: kemitix
  stackexchange:
  linkedin:
  pinterest:

disqus:
  shortname: kemitix-code

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
