# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kemitix Code
email: pcampbell@kemitix.net
url: "https://kemitix.github.io"
github_username: kemitix
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_codary: false
exclude: ["Gemfile", "Gemfile.lock", ".idea"]
comments: true
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: kemitix/hydejack
author:
  name: Paul Campbell
  picture: images/paul-campbell.jpg
  email: pcampbell@kemitix.net
  github: kemitix
disqus: kemitix-code
